{% set version = "0.21.0" %}
{% set pypi_package_name = "u8darts" %}

package:
  name: u8darts
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_package_name[0] }}/{{ pypi_package_name }}/{{ pypi_package_name }}-{{ version }}.tar.gz
  sha256: 9da9045cac29e071c3d80c2b671dc4641a2b09ed5fc7565ac87037e6e9cfea81

build:
  number: 0
  noarch: python

outputs:
  - name: u8darts
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - holidays >=0.11.1
        - ipython >=7.0.0
        - joblib >=0.16.0
        - lightgbm >=2.2.3
        - matplotlib-base >=3.3.0
        - nfoursid >=0.1.0
        - numpy >=1.19.0
        - pandas >=1.0.5
        - requests >=2.22.0
        - scikit-learn >=1.0.1
        - scipy >=1.3.2
        - statsforecast >=0.5.2
        - statsmodels >=0.13.0
        - tqdm >=4.60.0
        - xarray >=0.17.0
    test:
      imports:
        - darts
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

  - name: u8darts-torch
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning>=1.5.0
        - pytorch >=1.8.0

    test:
      imports:
        - darts
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

  - name: u8darts-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pmdarima >=1.8.0
        - pystan >=2.19.1.1,<3.0.0.0
        - pytorch-lightning >=1.5.0
        - pytorch >=1.8.0
        - tbats >=1.1.0

    test:
      imports:
        - darts
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

about:
  home: https://unit8co.github.io/darts/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A python library for easy manipulation and forecasting of time series.
  dev_url: https://github.com/unit8co/darts
  doc_url: https://unit8co.github.io/darts/

extra:
  recipe-maintainers:
    - hrzn
    - tomasvanpottelbergh
    - gnwhr
