{% set version = "0.23.0" %}
{% set pypi_package_name = "u8darts" %}

package:
  name: u8darts
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_package_name[0] }}/{{ pypi_package_name }}/{{ pypi_package_name }}-{{ version }}.tar.gz
  sha256: 4556f3a82e920ccb8bb70e6f05afa0514c8f0353d297e1b6a6a022cb3c7ef82b

build:
  number: 0
  noarch: python

outputs:
  - name: u8darts
    build:
      noarch: python
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - catboost >=1.0.6
        - holidays >=0.11.1
        - joblib >=0.16.0
        - lightgbm >=3.2.0
        - matplotlib-base >=3.3.0
        - nfoursid >=1.0.0
        - numpy >=1.19.0
        - pandas >=1.0.5
        - pmdarima >=1.8.0
        - prophet >=1.1.1
        - pyod >=0.9.5
        - requests >=2.22.0
        - scikit-learn >=1.0.1
        - scipy >=1.3.2
        - shap >=0.40.0
        - statsforecast >=1.0.0
        - statsmodels >=0.13.0
        - tbats >=1.1.0
        - tqdm >=4.60.0
        - xarray >=0.17.0
        - xgboost >=1.6.0
    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_models
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

  - name: u8darts-torch
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning>=1.5.0
        - pytorch >=1.8.0

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_models
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

  - name: u8darts-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning >=1.5.0
        - pytorch >=1.8.0

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_models
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
      source_files:
        - darts
      commands:
        - pytest darts/tests
      requires:
        - pip
        - testfixtures
        - pytest

about:
  home: https://unit8co.github.io/darts/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A python library for user-friendly forecasting and anomaly detection on time series.
  dev_url: https://github.com/unit8co/darts
  doc_url: https://unit8co.github.io/darts/

extra:
  recipe-maintainers:
    - hrzn
    - dennisbader
    - tomasvanpottelbergh
