{% set name = "u8darts" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 724878deb4cf6ccac7bd20513065fbcace9857839a29e3902ea1aa14cc10484d

build:
  number: 0
  skip: true  # [py<38]
  patches:
    # For py38 one test fails after the change in this PR:
    # https://github.com/unit8co/darts/pull/1932/files
    # in the file darts/tests/test_timeseries.py
    # 
    # For py>38 using scipy 1.11.3 and xarray 2023.6.0
    # solves the problem without patch.
    # 
    # In this patch we restore one line reverting to the
    # previous way of invoking the 'resample' function
    - patches/001_fix-resample-restore-loffset.patch  # [py<39]

outputs:
  - name: u8darts
    requirements:
      build:
        - patch  # [py<39 and not win]
        - m2-patch  # [py<39 and win]
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - holidays >=0.11.1
        - joblib >=0.16.0
        - matplotlib-base >=3.3.0
        - nfoursid >=1.0.0
        - numpy >=1.19.0
        - pandas >=1.0.5,<2.0.0  # [py<39]
        - pandas >=1.0.5         # [py>=39]
        - pmdarima >=1.8.0
        - pyod >=0.9.5
        - requests >=2.22.0
        - scikit-learn >=1.0.1
        - scipy >=1.3.2
        - shap >=0.40.0
        - statsforecast >=1.4.0
        - statsmodels >=0.14.0
        - tbats >=1.1.0
        - tqdm >=4.60.0
        - typing-extensions
        - xarray >=0.17.0
        - xgboost >=1.6.0

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
        - darts.utils.historical_forecasts
      requires:
        - pip
        - testfixtures
        - pytest
      source_files:
        - darts
      commands:
        - pip check
        - pytest darts/tests

  - name: u8darts-notorch
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("u8darts", exact=True) }}
        - catboost >=1.0.6
        - lightgbm >=3.2.0
        - prophet >=1.1.1

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
        - darts.utils.historical_forecasts
      requires:
        - pip
        - testfixtures
        - pytest
      source_files:
        - darts
      commands:
        - pip check
        - pytest darts/tests

  - name: u8darts-torch
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning >=1.5.0
        - tensorboardx >=2.1
        - pytorch >=1.8.0

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
        - darts.utils.historical_forecasts
      requires:
        - pip
        - testfixtures
        - pytest
      source_files:
        - darts
      commands:
        - pip check
        - pytest darts/tests

  - name: u8darts-all
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("u8darts", exact=True) }}
        - pytorch-lightning >=1.5.0
        - tensorboardx >=2.1
        - pytorch >=1.8.0
        - catboost >=1.0.6
        - lightgbm >=3.2.0
        - prophet >=1.1.1

    test:
      imports:
        - darts
        - darts.ad
        - darts.ad.aggregators
        - darts.ad.anomaly_model
        - darts.ad.detectors
        - darts.ad.scorers
        - darts.dataprocessing
        - darts.dataprocessing.dtw
        - darts.dataprocessing.encoders
        - darts.dataprocessing.transformers
        - darts.datasets
        - darts.explainability
        - darts.metrics
        - darts.models
        - darts.tests
        - darts.tests.dataprocessing
        - darts.tests.dataprocessing.transformers
        - darts.tests.utils
        - darts.utils
        - darts.utils.data
        - darts.utils.historical_forecasts
      requires:
        - pip
        - testfixtures
        - pytest
      source_files:
        - darts
      commands:
        - pip check
        - pytest darts/tests

about:
  home: https://unit8co.github.io/darts/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A python library for user-friendly forecasting and anomaly detection on time series.
  description: |
    Darts is a Python library for user-friendly forecasting and anomaly detection on time series. 
    It contains a variety of models, from classics such as ARIMA to deep neural networks. 
    The forecasting models can all be used in the same way, using fit() and predict() functions, 
    similar to scikit-learn. The library also makes it easy to backtest models, combine the 
    predictions of several models, and take external data into account. Darts supports both 
    univariate and multivariate time series and models. The ML-based models can be trained on 
    potentially large datasets containing multiple time series, and some of the models offer a 
    rich support for probabilistic forecasting.
  dev_url: https://github.com/unit8co/darts
  doc_url: https://unit8co.github.io/darts/

extra:
  recipe-maintainers:
    - hrzn
    - dennisbader
